model = "gpt-5.4"
model_reasoning_effort = "xhigh"
approval_policy = "on-request"
hide_agent_reasoning = true
sandbox_mode = "workspace-write"
network_access = true

notify = ["bash", "-c", "source $HOME/.codex/notify.sh"]
personality = "pragmatic"

[tui]
notifications = [
  "agent-turn-complete",
  "approval-requested"
]

[features]
skills = true
web_search_request = true

[mcp_servers.serena]
command = "uvx"
args = [
  "--from", "git+https://github.com/oraios/serena",
  "serena",
  "start-mcp-server",
  "--context", "codex",
  "--enable-web-dashboard", "False",
]

[mcp_servers.phpstorm]
command = "npx"
args = [
  "mcp-remote",
  "http://localhost:64342/sse"
]

[mcp_servers.phpstorm.tools.get_file_text_by_path]
approval_mode = "approve"

[mcp_servers.phpstorm.tools.search_in_files_by_text]
approval_mode = "approve"

[notice.model_migrations]
"gpt-5.1-codex-max" = "gpt-5.2-codex"
"gpt-5.3-codex" = "gpt-5.4"

[projects."/Users/shogo.kawase/ghq/github.com/PRTIMES/prtimes"]
trust_level = "trusted"

[plugins."github@openai-curated"]
enabled = true

[plugins."google-drive@openai-curated"]
enabled = true
