[aws.region_aliases]
ap-northeast-1 = "tokyo"

[directory]
truncate_to_repo = false
truncation_length = 0

[nodejs]
disabled = true

[package]
disabled = true

[time]
disabled = false
format = "[$time]($style) "
style = "yellow"
